[package]
name = "jugend-forscht-receiver"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
package-parser = { path = "package-parser" }
rand = "0.9.2"
rusqlite = { version = "0.38.0", features = ["bundled"] }
serialport = "4.8.1"
